#!/bin/bash


COAPCLIENT=/usr/local/bin/coap-client
METHOD=$1
ADDR=$2
RESOURCE=$3

#Send Coap Request.
$COAPCLIENT -m $METHOD "coap://[${ADDR}]/${RESOURCE}"

#Wait for a second.
sleep 0.5

#Query for execution time.
$COAPCLIENT -m get "coap://[${ADDR}]/test/timing"
