#!/bin/bash


COAPCLIENT=/usr/local/bin/coap-client
METHOD=$1
ADDR=$2
RESOURCE=$3


while [[ 1 ]]; do
	#Send Coap Request.
	$COAPCLIENT -m $METHOD "coap://[${ADDR}]/${RESOURCE}"
	sleep 0.5

	#Query for execution time.
	$COAPCLIENT -m get "coap://[${ADDR}]/test/timing"
	sleep 0.5
done;
